version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "yuno"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "gallery"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "yuno"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
    volumes:
      - mongodb_data:/data/db

volumes:
  mariadb_data:
    driver: local
  postgres_data:
    driver: local
  mongodb_data:
    driver: local